name: mfm
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - jupyter
  - numpy
  - seaborn
  - scikit-learn
  - matplotlib
  - seaborn
  - pydot
  - pqdm
  - dask
  - pyarrow
  - fastparquet
  - ipdb
  - openpyxl
  - nbstripout
  - fire
  - pip
  - pip:
    - wfdb
    - pqdm
    - nbstripout
    - ipdb
    - fire
